# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='added time')),
                ('abstract', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Useless',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='added time')),
                ('abstract', models.CharField(max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspapers.Location')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspapers.Sources')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspapers.Location'),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspapers.Sources'),
        ),
    ]
